blank_issues_enabled: false
# Define the templates and their associations
issue_templates:
  # Template for bug reports
  - name: Bug Report
    about: Create a bug report to help us improve
    labels: bug
    assignees: ''
    file: bug_report.md

  # Template for feature requests
  - name: Feature Request
    about: Suggest an idea or enhancement
    labels: enhancement
    assignees: ''
    file: feature.md

  # Generic template for other types of issues
  - name: Generic Issue
    about: Create a general issue
    labels: ''
    assignees: ''
    file: issue-template.md
