name: Add Branch Prefix

on:
  push:
    branches:
      - "*"

# This will rename and add the USNP- prefix when a branch is pushed only if it does not already have the prefix

jobs:
  add-prefix:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch name contains prefix
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          if [[ $BRANCH_NAME == USNP-* ]]; then
            echo "Branch name already contains prefix."
            exit 0
          else
            ISSUE_NUMBER=$(echo "${{ github.event.head_commit.message }}" | jq -r 'match("#(\\d+)" | .captures[0].string) | .[1]')
            PREFIXED_BRANCH_NAME="USNP-$ISSUE_NUMBER-$BRANCH_NAME"
            git branch -m $PREFIXED_BRANCH_NAME
            git push origin $PREFIXED_BRANCH_NAME
          fi
