name: Deploy Lambda Function

on:
  push:
    branches:
      - DR-79-deploy-lambdas

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code --function-name whatever --zip-file fileb://./backend/lambda/whatever/whatever.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
